apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"thehive-data-pvc","namespace":"thehive"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}
  creationTimestamp: "2026-05-19T10:16:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: thehive-data-pvc
  namespace: thehive
  resourceVersion: "3657492"
  uid: 311bb1af-8bc0-4090-80a1-760b5847a69a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Pending
