apiVersion: v1
data:
  admin-password: c2VjcmV0
  api-key: QzlQVTNjMEtOSTZ3VVptT2pVVmYySCt6aUg1K0EyTS8=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"api-key":"QzlQVTNjMEtOSTZ3VVptT2pVVmYySCt6aUg1K0EyTS8="},"kind":"Secret","metadata":{"annotations":{},"name":"thehive-soc-apikey","namespace":"thehive"}}
  creationTimestamp: "2026-05-04T06:44:21Z"
  name: thehive-soc-apikey
  namespace: thehive
  resourceVersion: "3593292"
  uid: 191a77bf-06f3-49c8-b5da-3cb8d4dc0360
type: Opaque
