[k3s_master]
soc-master ansible_host=192.168.122.35 ansible_user=ismail

[k3s_workers]
worker1 ansible_host=192.168.122.10 ansible_user=ismail
worker2 ansible_host=192.168.122.95 ansible_user=ismail

[suricata_nodes]
worker1 ansible_host=192.168.122.10 ansible_user=ismail

[wazuh_agents]
soc-master ansible_host=192.168.122.35 ansible_user=ismail
worker1 ansible_host=192.168.122.10 ansible_user=ismail
worker2 ansible_host=192.168.122.95 ansible_user=ismail

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
