---
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Deploy k3s master
  hosts: k3s_master
  become: yes
  roles:
    - k3s_server

- name: Deploy k3s workers
  hosts: k3s_workers
  become: yes
  roles:
    - k3s_agent

- name: Deploy Wazuh agents on Linux hosts
  hosts: wazuh_agents
  become: yes
  roles:
    - wazuh-agent

- name: Deploy SOC tools on worker2
  hosts: worker2
  become: yes
  roles:
    - soc-tools
